name: chrislee
favicon: null
layout_spectrum: 0.0655062657315284
typography_spectrum: 0.25325123802758753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6577568394131958
  lightness: 0.0515922571066767
  saturation: 0.8868523226119578
  rhythmicContrast: 0.2566964759025723
purpose: []
