name: chrislee
favicon: null
layout_spectrum: 0.60941
typography_spectrum: 0.74586
title: lchrs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f2f0'
    - '#c7c6c2'
    - '#0b1c0c'
    - '#7f8681'
    - '#353a27'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
